# テスト対象から除外
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - "db/schema.rb"

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# Guradのwatch設定はブロックが長くなるのが避けられない
Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

# TODO: ドキュメント用のコメントは後で書く
Style/Documentation:
  Enabled: false

# 1行の長さ上限は120とする
Metrics/LineLength:
  Max: 120

# Railsで自動生成されたコードではmodule定義の形式はそのままとする。
Style/ClassAndModuleChildren:
  Enabled: false
